import '@style/globals.css'

import Nav from '@components/Nav'
import Footer from '@components/Footer'
import Provider from '@components/Provider.jsx'
export const metadata = {
  title: 'Dev Stack',
  description: 'Generated by Dev Stack',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
      <Provider>
      <main>
     <Nav/>
      {children}
      <Footer/>
      </main>
      </Provider>
      </body>
    </html>
  )
}
